# Generated by Django 2.2.2 on 2019-10-04 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bank_cash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='charity_mem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_name', models.CharField(max_length=100)),
                ('Child', models.IntegerField(default=0)),
                ('Arab', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='paid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_value', models.IntegerField()),
                ('charity_mem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.charity_mem')),
                ('paid_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.bank_cash')),
            ],
        ),
        migrations.CreateModel(
            name='incoming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='s')),
                ('date_publish', models.DateField(auto_now_add=True)),
                ('paid_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.bank_cash')),
            ],
        ),
    ]
