# Generated by Django 2.2.2 on 2019-10-04 20:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('balance', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'صندوق و خزانه',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, null=True, verbose_name='عنوان')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ')),
                ('amount', models.IntegerField(verbose_name='مقدار')),
                ('discription', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name_plural': 'هزینه و خرج',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, null=True, verbose_name='عنوان')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ')),
                ('amount', models.IntegerField(verbose_name='مقدار')),
                ('paid_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Income_Cat', to='manager.Category')),
            ],
            options={
                'verbose_name_plural': 'واریز و دریافت',
            },
        ),
        migrations.CreateModel(
            name='Madadjoo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=20, null=True)),
                ('l_name', models.CharField(max_length=40, null=True)),
                ('address', models.TextField(default='here')),
                ('job', models.CharField(max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1, null=True)),
                ('description', models.TextField(default='nothing')),
                ('is_arab', models.BooleanField(default=False)),
                ('sonat_religion', models.BooleanField()),
                ('nationality', models.CharField(choices=[('IR', 'Iran'), ('Af', 'Afghan'), ('Pa', 'Pakistan')], max_length=2)),
            ],
            options={
                'verbose_name_plural': 'مددجویان',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name_plural': 'روشهای پرداخت',
            },
        ),
        migrations.RemoveField(
            model_name='incoming',
            name='paid_for',
        ),
        migrations.RemoveField(
            model_name='paid',
            name='charity_mem',
        ),
        migrations.RemoveField(
            model_name='paid',
            name='paid_for',
        ),
        migrations.AlterModelOptions(
            name='volunteer',
            options={'verbose_name_plural': 'نیکوکاران'},
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='F_name',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='address',
            field=models.TextField(default='here'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='description',
            field=models.TextField(default='nothing'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='f_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='is_arab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='job',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='join_by',
            field=models.CharField(choices=[('T', 'Telegram'), ('W', 'WebSite'), ('I', 'Instagram'), ('F', 'FriendRelation')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='l_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='sex',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1, null=True),
        ),
        migrations.DeleteModel(
            name='bank_cash',
        ),
        migrations.DeleteModel(
            name='charity_mem',
        ),
        migrations.DeleteModel(
            name='incoming',
        ),
        migrations.DeleteModel(
            name='paid',
        ),
        migrations.AddField(
            model_name='income',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.PaymentMethod', verbose_name='پرداخت با'),
        ),
        migrations.AddField(
            model_name='income',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Volunteer'),
        ),
        migrations.AddField(
            model_name='expense',
            name='madadjoo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='manager.Madadjoo', verbose_name='شخص استفاده کننده'),
        ),
        migrations.AddField(
            model_name='expense',
            name='paid_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Expense_Cat', to='manager.Category', verbose_name='پرداخت برای'),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.PaymentMethod', verbose_name='پرداخت با'),
        ),
    ]
